package com.example.lifetogether.ui.navigation

object AppRoutes {
    const val ADMIN_GROCERY_CATEGORIES_SCREEN = "admin_grocery_categories"
    const val ADMIN_GROCERY_SUGGESTIONS_SCREEN = "admin_grocery_suggestions"
    const val LOADING_SCREEN = "loading"
    const val HOME_SCREEN = "home"
    const val PROFILE_SCREEN = "profile"
    const val FAMILY_SCREEN = "family"
    const val SETTINGS_SCREEN = "settings"
    const val LOGIN_SCREEN = "login"
    const val SIGNUP_SCREEN = "signup"
    const val GROCERY_LIST_SCREEN = "grocery"
    const val RECIPES_SCREEN = "recipes"
    const val RECIPE_DETAILS_SCREEN = "recipe_details"
    const val CREATE_RECIPE_SCREEN = "create_recipe_screen"
    const val RECIPE_ID_ARG = "recipeId"
    const val GUIDES_SCREEN = "guides"
    const val GUIDE_GRAPH = "guide_graph"
    const val GUIDE_GRAPH_ROUTE = "guide_graph/{guideId}"
    const val GUIDE_DETAILS_SCREEN = "guide_details"
    const val GUIDE_STEP_PLAYER_SCREEN = "guide_step_player"
    const val GUIDE_CREATE_SCREEN = "guide_create"
    const val GUIDE_ID_ARG = "guideId"
    const val GALLERY_SCREEN = "gallery"
    const val ALBUM_MEDIA_SCREEN = "album_media"
    const val ALBUM_MEDIA_ID_ARG = "albumId"
    const val GALLERY_MEDIA_SCREEN = "gallery_media"
    const val GALLERY_MEDIA_ALBUM_ARG = "albumId"
    const val GALLERY_MEDIA_INDEX_ARG = "initialIndex"
    const val TIP_TRACKER_GRAPH = "tip_tracker_graph"
    const val TIP_TRACKER_SCREEN = "tip_tracker"
    const val TIP_STATISTICS_SCREEN = "tip_statistics"
    // ... other routes
}
