package com.example.lifetogether.ui.navigation

interface Navigator {
    fun navigateToAdminGroceryCategories()
    fun navigateToAdminGrocerySuggestions()
    fun navigateToHome()
    fun navigateToProfile()
    fun navigateToFamily()
    fun navigateToSettings()
    fun navigateToLogin()
    fun navigateToSignUp()
    fun navigateBack()
    fun navigateToGroceryList()
    fun navigateToRecipes()
    fun navigateToRecipeDetails(recipeId: String? = null)
    fun navigateToGuides()
    fun navigateToGuideDetails(guideId: String)
    fun navigateToGuideStepPlayer()
    fun navigateToGuideCreate()
    fun navigateToGallery()
    fun navigateToAlbumMedia(albumId: String)
    fun navigateToGalleryMedia(albumId: String, initialIndex: Int)
    fun navigateToTipTracker()
    fun navigateToTipStatistics()
    fun navigateToLists()
    fun navigateToListDetail(listId: String)
    fun navigateToListEntryDetails(listId: String, entryId: String? = null)
}
